name: Run canary builds
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "29 1 * * 1"
  workflow_dispatch:
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:devel
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Install deps
        run: apt-get update && apt-get install -y gnome-common libnautilus-extension-dev libgtk-4-dev python3-gi python3-docutils
      - name: Test build
        run: ./autogen.sh && make && make install
      - name: Run tests
        run: python3 ./dropbox_test.py
      - name: Check that latest OS version is supported
        run: |
          . ./distro-info.sh
          . /etc/os-release
          if [[ "$UBUNTU_CODENAMES" == *"$VERSION_CODENAME"* ]]; then
            echo "$NAME $VERSION is supported."
          else
            echo "$NAME $VERSION needs to be added to distro-info.sh in order to produce the correct repo."
            exit 1
          fi

  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:rawhide
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Install deps
        run: dnf install -y gnome-common nautilus-devel gtk4-devel python3-docutils python3-gobject
      - name: Test build
        run: ./autogen.sh && make && make install
      - name: Run tests
        run: python3 ./dropbox_test.py
      - name: Check that latest OS version is supported
        run: |
          . ./distro-info.sh
          . /etc/os-release
          if [[ "$FEDORA_CODENAMES" == *"$VERSION_ID"* ]]; then
            echo "Fedora $VERSION_ID is supported."
          else
            echo "Fedora $VERSION_ID needs to be added to distro-info.sh in order to produce the correct repo."
            exit 1
          fi
