name: Run canary builds
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "29 1 * * 1"
  workflow_dispatch:
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:devel
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Install deps
        run: ./install-apt-deps.sh
      - name: Test build
        run: ./autogen.sh && make && make install
      - name: Run tests
        run: python3 ./dropbox_test.py
      - name: Check that latest OS version is supported
        run: |
          . ./distro-info.sh
          . /etc/os-release
          ./check-distro-info-support.sh "$VERSION_CODENAME" "$NAME $VERSION" "$UBUNTU_CODENAMES"

  debian:
    runs-on: ubuntu-latest
    container:
      image: debian:sid
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Install deps
        run: ./install-apt-deps.sh
      - name: Test build
        run: ./autogen.sh && make && make install
      - name: Run tests
        run: python3 ./dropbox_test.py
      - name: Check that latest OS version is supported
        run: |
          . ./distro-info.sh
          . /etc/os-release
          ./check-distro-info-support.sh "$VERSION_CODENAME" "$PRETTY_NAME" "$DEBIAN_CODENAMES"

  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:rawhide
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Install deps
        run: ./install-rpm-deps.sh
      - name: Test build
        run: ./autogen.sh && make && make install
      - name: Run tests
        run: python3 ./dropbox_test.py
      - name: Check that latest OS version is supported
        run: |
          . ./distro-info.sh
          . /etc/os-release
          ./check-distro-info-support.sh "$VERSION_ID" "Fedora $VERSION_ID" "$FEDORA_CODENAMES"
